-- =============================================
-- Worship Song Library — 15 Classic Hymns Seed
-- Songs 16-30 (adding to existing 1-15)
-- =============================================
USE worship_db;

-- New hashtags needed
INSERT IGNORE INTO hashtags (name, category) VALUES
('classic', 'style'),
('hymn', 'style');

-- Song 16: Holy Holy Holy
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(16, 'Holy Holy Holy', 'Reginald Heber', 'John B. Dykes', 'english',
'[Verse 1]\nHoly holy holy Lord God Almighty\nEarly in the morning our song shall rise to Thee\nHoly holy holy merciful and mighty\nGod in three Persons blessed Trinity\n\n[Verse 2]\nHoly holy holy all the saints adore Thee\nCasting down their golden crowns around the glassy sea\nCherubim and seraphim falling down before Thee\nWhich wert and art and evermore shalt be\n\n[Verse 3]\nHoly holy holy though the darkness hide Thee\nThough the eye of sinful man Thy glory may not see\nOnly Thou art holy there is none beside Thee\nPerfect in power in love and purity\n\n[Verse 4]\nHoly holy holy Lord God Almighty\nAll Thy works shall praise Thy Name in earth and sky and sea\nHoly holy holy merciful and mighty\nGod in three Persons blessed Trinity',
'[Verse 1]\n[D]Holy holy [G]holy [D]Lord God Al[A]mighty\n[D]Early in the [G]morning our [E]song shall rise to [A]Thee\n[D]Holy holy [G]holy [D]merci[Bm]ful and [F#m]mighty\n[G]God in three [D]Persons [A]blessed Trini[D]ty\n\n[Verse 2]\n[D]Holy holy [G]holy [D]all the saints a[A]dore Thee\n[D]Casting down their [G]golden crowns a[E]round the glassy [A]sea\n[D]Holy holy [G]holy [D]thou the [Bm]darkness [F#m]hide Thee\n[G]Which wert and [D]art and [A]evermore shalt [D]be\n\n[Verse 3]\n[D]Holy holy [G]holy [D]though the dark[A]ness hide Thee\n[D]Though the eye of [G]sinful man Thy [E]glory may not [A]see\n[D]Only Thou art [G]holy [D]there is [Bm]none be[F#m]side Thee\n[G]Perfect in [D]power in [A]love and puri[D]ty\n\n[Verse 4]\n[D]Holy holy [G]holy [D]Lord God Al[A]mighty\n[D]All Thy works shall [G]praise Thy Name in [E]earth and sky and [A]sea\n[D]Holy holy [G]holy [D]merci[Bm]ful and [F#m]mighty\n[G]God in three [D]Persons [A]blessed Trini[D]ty',
'D', 0, 100, '4/4', 'Verse1, Verse2, Verse3, Verse4', 1, TRUE);

-- Song 17: It Is Well With My Soul
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(17, 'It Is Well With My Soul', 'Horatio Spafford', 'Philip Bliss', 'english',
'[Verse 1]\nWhen peace like a river attendeth my way\nWhen sorrows like sea billows roll\nWhatever my lot Thou hast taught me to say\nIt is well it is well with my soul\n\n[Chorus]\nIt is well with my soul\nIt is well it is well with my soul\n\n[Verse 2]\nThough Satan should buffet though trials should come\nLet this blest assurance control\nThat Christ hath regarded my helpless estate\nAnd hath shed His own blood for my soul\n\n[Verse 3]\nMy sin oh the bliss of this glorious thought\nMy sin not in part but the whole\nIs nailed to the cross and I bear it no more\nPraise the Lord praise the Lord O my soul\n\n[Verse 4]\nAnd Lord haste the day when my faith shall be sight\nThe clouds be rolled back as a scroll\nThe trump shall resound and the Lord shall descend\nEven so it is well with my soul',
'[Verse 1]\nWhen [C]peace like a [C/E]river at[F]tendeth my [C]way\nWhen [F]sorrows like [C]sea billows [G]roll\nWhat[C]ever my [C/E]lot Thou hast [F]taught me to [C]say\nIt is [F]well it is [G]well with my [C]soul\n\n[Chorus]\nIt is [Am]well [Em]with my [F]soul\nIt is [C]well it is [G]well with my [C]soul\n\n[Verse 2]\nThough [C]Satan should [C/E]buffet though [F]trials should [C]come\nLet [F]this blest as[C]surance con[G]trol\nThat [C]Christ hath re[C/E]garded my [F]helpless es[C]tate\nAnd hath [F]shed His own [G]blood for my [C]soul\n\n[Verse 3]\nMy [C]sin oh the [C/E]bliss of this [F]glorious [C]thought\nMy [F]sin not in [C]part but the [G]whole\nIs [C]nailed to the [C/E]cross and I [F]bear it no [C]more\nPraise the [F]Lord praise the [G]Lord O my [C]soul\n\n[Verse 4]\nAnd [C]Lord haste the [C/E]day when my [F]faith shall be [C]sight\nThe [F]clouds be rolled [C]back as a [G]scroll\nThe [C]trump shall re[C/E]sound and the [F]Lord shall des[C]cend\nEven [F]so it is [G]well with my [C]soul',
'C', 0, 84, '4/4', 'Verse1, Chorus, Verse2, Chorus, Verse3, Chorus, Verse4, Chorus', 1, TRUE);

-- Song 18: Be Thou My Vision
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(18, 'Be Thou My Vision', 'Dallan Forgaill', 'Traditional Irish', 'english',
'[Verse 1]\nBe Thou my Vision O Lord of my heart\nNaught be all else to me save that Thou art\nThou my best thought by day or by night\nWaking or sleeping Thy presence my light\n\n[Verse 2]\nBe Thou my Wisdom and Thou my true Word\nI ever with Thee and Thou with me Lord\nThou my great Father I Thy true son\nThou in me dwelling and I with Thee one\n\n[Verse 3]\nRiches I heed not nor man''s empty praise\nThou mine Inheritance now and always\nThou and Thou only first in my heart\nHigh King of Heaven my Treasure Thou art\n\n[Verse 4]\nHigh King of Heaven my victory won\nMay I reach Heaven''s joys O bright Heaven''s Sun\nHeart of my own heart whatever befall\nStill be my Vision O Ruler of all',
'[Verse 1]\n[D]Be Thou my [G]Vision O [D]Lord of my [Bm]heart\n[G]Naught be all [A]else to me [G]save that Thou [D]art\n[D]Thou my best [G]thought by [D]day or by [Bm]night\n[G]Waking or [A]sleeping Thy [G]presence my [D]light\n\n[Verse 2]\n[D]Be Thou my [G]Wisdom and [D]Thou my true [Bm]Word\n[G]I ever [A]with Thee and [G]Thou with me [D]Lord\n[D]Thou my great [G]Father [D]I Thy true [Bm]son\n[G]Thou in me [A]dwelling and [G]I with Thee [D]one\n\n[Verse 3]\n[D]Riches I [G]heed not nor [D]man''s empty [Bm]praise\n[G]Thou mine In[A]heritance [G]now and al[D]ways\n[D]Thou and Thou [G]only [D]first in my [Bm]heart\n[G]High King of [A]Heaven my [G]Treasure Thou [D]art\n\n[Verse 4]\n[D]High King of [G]Heaven my [D]victory [Bm]won\n[G]May I reach [A]Heaven''s joys O [G]bright Heaven''s [D]Sun\n[D]Heart of my [G]own heart what[D]ever be[Bm]fall\n[G]Still be my [A]Vision O [G]Ruler of [D]all',
'D', 0, 100, '3/4', 'Verse1, Verse2, Verse3, Verse4', 1, TRUE);

-- Song 19: Come Thou Fount Of Every Blessing
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(19, 'Come Thou Fount Of Every Blessing', 'Robert Robinson', 'Asahel Nettleton', 'english',
'[Verse 1]\nCome Thou Fount of every blessing\nTune my heart to sing Thy grace\nStreams of mercy never ceasing\nCall for songs of loudest praise\nTeach me some melodious sonnet\nSung by flaming tongues above\nPraise the mount I''m fixed upon it\nMount of Thy redeeming love\n\n[Verse 2]\nHere I raise my Ebenezer\nHither by Thy help I''ve come\nAnd I hope by Thy good pleasure\nSafely to arrive at home\nJesus sought me when a stranger\nWandering from the fold of God\nHe to rescue me from danger\nInterposed His precious blood\n\n[Verse 3]\nO to grace how great a debtor\nDaily I''m constrained to be\nLet Thy goodness like a fetter\nBind my wandering heart to Thee\nProne to wander Lord I feel it\nProne to leave the God I love\nHere''s my heart O take and seal it\nSeal it for Thy courts above',
'[Verse 1]\n[D]Come Thou [G]Fount of [D]every blessing\n[D]Tune my [G]heart to [A]sing Thy grace\n[D]Streams of [G]mercy [D]never ceasing\n[D]Call for [G]songs of [A]loudest praise\n[D]Teach me [G]some mel[D]odious sonnet\n[D]Sung by [G]flaming [A]tongues above\n[D]Praise the [G]mount I''m [D]fixed upon it\n[D]Mount of [A]Thy redeeming [D]love\n\n[Verse 2]\n[D]Here I [G]raise my [D]Ebenezer\n[D]Hither [G]by Thy [A]help I''ve come\n[D]And I [G]hope by [D]Thy good pleasure\n[D]Safely [G]to ar[A]rive at home\n[D]Jesus [G]sought me [D]when a stranger\n[D]Wandering [G]from the [A]fold of God\n[D]He to [G]rescue [D]me from danger\n[D]Inter[A]posed His precious [D]blood\n\n[Verse 3]\n[D]O to [G]grace how [D]great a debtor\n[D]Daily [G]I''m con[A]strained to be\n[D]Let Thy [G]goodness [D]like a fetter\n[D]Bind my [G]wandering [A]heart to Thee\n[D]Prone to [G]wander [D]Lord I feel it\n[D]Prone to [G]leave the [A]God I love\n[D]Here''s my [G]heart O [D]take and seal it\n[D]Seal it [A]for Thy courts a[D]bove',
'D', 0, 100, '3/4', 'Verse1, Verse2, Verse3', 1, TRUE);

-- Song 20: Rock Of Ages
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(20, 'Rock Of Ages', 'Augustus Toplady', 'Thomas Hastings', 'english',
'[Verse 1]\nRock of Ages cleft for me\nLet me hide myself in Thee\nLet the water and the blood\nFrom Thy wounded side which flowed\nBe of sin the double cure\nSave from wrath and make me pure\n\n[Verse 2]\nCould my tears forever flow\nCould my zeal no languor know\nThese for sin could not atone\nThou must save and Thou alone\nIn my hand no price I bring\nSimply to the cross I cling\n\n[Verse 3]\nWhile I draw this fleeting breath\nWhen mine eyes shall close in death\nWhen I soar to worlds unknown\nSee Thee on Thy judgment throne\nRock of Ages cleft for me\nLet me hide myself in Thee',
'[Verse 1]\n[D]Rock of [A]Ages [D]cleft for me\n[G]Let me [D]hide my[A]self in [D]Thee\n[D]Let the [A]water [D]and the blood\n[G]From Thy [D]wounded [A]side which [D]flowed\n[D]Be of [G]sin the [D]double [A]cure\n[G]Save from [D]wrath and [A]make me [D]pure\n\n[Verse 2]\n[D]Could my [A]tears for[D]ever flow\n[G]Could my [D]zeal no [A]languor [D]know\n[D]These for [A]sin could [D]not atone\n[G]Thou must [D]save and [A]Thou a[D]lone\n[D]In my [G]hand no [D]price I [A]bring\n[G]Simply [D]to the [A]cross I [D]cling\n\n[Verse 3]\n[D]While I [A]draw this [D]fleeting breath\n[G]When mine [D]eyes shall [A]close in [D]death\n[D]When I [A]soar to [D]worlds unknown\n[G]See Thee [D]on Thy [A]judgment [D]throne\n[D]Rock of [G]Ages [D]cleft for [A]me\n[G]Let me [D]hide my[A]self in [D]Thee',
'D', 0, 88, '3/4', 'Verse1, Verse2, Verse3', 1, TRUE);

-- Song 21: Joyful Joyful We Adore Thee
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(21, 'Joyful Joyful We Adore Thee', 'Henry Van Dyke', 'Ludwig van Beethoven', 'english',
'[Verse 1]\nJoyful joyful we adore Thee\nGod of glory Lord of love\nHearts unfold like flowers before Thee\nOpening to the sun above\nMelt the clouds of sin and sadness\nDrive the dark of doubt away\nGiver of immortal gladness\nFill us with the light of day\n\n[Verse 2]\nAll Thy works with joy surround Thee\nEarth and heaven reflect Thy rays\nStars and angels sing around Thee\nCenter of unbroken praise\nField and forest vale and mountain\nFlowery meadow flashing sea\nChanting bird and flowing fountain\nCall us to rejoice in Thee\n\n[Verse 3]\nMortals join the mighty chorus\nWhich the morning stars began\nFather love is reigning o''er us\nBrother love binds man to man\nEver singing march we onward\nVictors in the midst of strife\nJoyful music leads us sunward\nIn the triumph song of life',
'[Verse 1]\n[G]Joyful [D]joyful [Em]we a[D]dore Thee\n[C]God of [G]glory [D]Lord of [G]love\n[G]Hearts un[D]fold like [Em]flowers be[D]fore Thee\n[C]Opening [G]to the [D]sun a[G]bove\n[G]Melt the [D]clouds of [Em]sin and [D]sadness\n[C]Drive the [G]dark of [D]doubt a[G]way\n[G]Giver [D]of im[Em]mortal [D]gladness\n[C]Fill us [G]with the [D]light of [G]day\n\n[Verse 2]\n[G]All Thy [D]works with [Em]joy sur[D]round Thee\n[C]Earth and [G]heaven re[D]flect Thy [G]rays\n[G]Stars and [D]angels [Em]sing a[D]round Thee\n[C]Center [G]of un[D]broken [G]praise\n[G]Field and [D]forest [Em]vale and [D]mountain\n[C]Flowery [G]meadow [D]flashing [G]sea\n[G]Chanting [D]bird and [Em]flowing [D]fountain\n[C]Call us [G]to re[D]joice in [G]Thee\n\n[Verse 3]\n[G]Mortals [D]join the [Em]mighty [D]chorus\n[C]Which the [G]morning [D]stars be[G]gan\n[G]Father [D]love is [Em]reigning [D]o''er us\n[C]Brother [G]love binds [D]man to [G]man\n[G]Ever [D]singing [Em]march we [D]onward\n[C]Victors [G]in the [D]midst of [G]strife\n[G]Joyful [D]music [Em]leads us [D]sunward\n[C]In the [G]triumph [D]song of [G]life',
'G', 0, 120, '4/4', 'Verse1, Verse2, Verse3', 1, TRUE);

-- Song 22: Crown Him With Many Crowns
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(22, 'Crown Him With Many Crowns', 'Matthew Bridges', 'George Elvey', 'english',
'[Verse 1]\nCrown Him with many crowns\nThe Lamb upon His throne\nHark how the heavenly anthem drowns\nAll music but its own\nAwake my soul and sing\nOf Him who died for thee\nAnd hail Him as thy matchless King\nThrough all eternity\n\n[Verse 2]\nCrown Him the Lord of life\nWho triumphed o''er the grave\nAnd rose victorious in the strife\nFor those He came to save\nHis glories now we sing\nWho died and rose on high\nWho died eternal life to bring\nAnd lives that death may die\n\n[Verse 3]\nCrown Him the Lord of love\nBehold His hands and side\nRich wounds yet visible above\nIn beauty glorified\nAll hail Redeemer hail\nFor Thou hast died for me\nThy praise and glory shall not fail\nThrough all eternity',
'[Verse 1]\n[D]Crown Him with [G]many [D]crowns\nThe [A]Lamb upon His [D]throne\n[D]Hark how the [G]heavenly [D]anthem [Em]drowns\nAll [A]music but its [D]own\n[A]Awake my [D]soul and [G]sing\nOf [D]Him who [A]died for [D]thee\nAnd [D]hail Him [G]as thy [D]matchless [Em]King\nThrough [A]all eter[D]nity\n\n[Verse 2]\n[D]Crown Him the [G]Lord of [D]life\nWho [A]triumphed o''er the [D]grave\n[D]And rose vic[G]torious [D]in the [Em]strife\nFor [A]those He came to [D]save\n[A]His glories [D]now we [G]sing\nWho [D]died and [A]rose on [D]high\nWho [D]died e[G]ternal [D]life to [Em]bring\nAnd [A]lives that death may [D]die\n\n[Verse 3]\n[D]Crown Him the [G]Lord of [D]love\nBe[A]hold His hands and [D]side\n[D]Rich wounds yet [G]visible [D]a[Em]bove\nIn [A]beauty glori[D]fied\n[A]All hail Re[D]deemer [G]hail\nFor [D]Thou hast [A]died for [D]me\nThy [D]praise and [G]glory [D]shall not [Em]fail\nThrough [A]all eter[D]nity',
'D', 0, 108, '4/4', 'Verse1, Verse2, Verse3', 1, TRUE);

-- Song 23: A Mighty Fortress Is Our God
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(23, 'A Mighty Fortress Is Our God', 'Martin Luther', 'Martin Luther', 'english',
'[Verse 1]\nA mighty fortress is our God\nA bulwark never failing\nOur helper He amid the flood\nOf mortal ills prevailing\nFor still our ancient foe\nDoth seek to work us woe\nHis craft and power are great\nAnd armed with cruel hate\nOn earth is not his equal\n\n[Verse 2]\nDid we in our own strength confide\nOur striving would be losing\nWere not the right man on our side\nThe man of God''s own choosing\nDost ask who that may be\nChrist Jesus it is He\nLord Sabaoth His Name\nFrom age to age the same\nAnd He must win the battle\n\n[Verse 3]\nAnd though this world with devils filled\nShould threaten to undo us\nWe will not fear for God hath willed\nHis truth to triumph through us\nThe Prince of Darkness grim\nWe tremble not for him\nHis rage we can endure\nFor lo his doom is sure\nOne little word shall fell him',
'[Verse 1]\n[C]A mighty [F]fortress [C]is our [G]God\nA [Am]bulwark [G]never [C]failing\n[C]Our helper [F]He a[C]mid the [G]flood\nOf [Am]mortal [G]ills pre[C]vailing\nFor [Am]still our [Em]ancient [F]foe\nDoth [C]seek to [G]work us [Am]woe\nHis [F]craft and [C]power are [G]great\nAnd [Am]armed with [F]cruel [G]hate\nOn [F]earth is [G]not his [C]equal\n\n[Verse 2]\n[C]Did we in [F]our own [C]strength con[G]fide\nOur [Am]striving [G]would be [C]losing\n[C]Were not the [F]right man [C]on our [G]side\nThe [Am]man of [G]God''s own [C]choosing\nDost [Am]ask who [Em]that may [F]be\n[C]Christ Jesus [G]it is [Am]He\n[F]Lord Sa[C]baoth His [G]Name\nFrom [Am]age to [F]age the [G]same\nAnd [F]He must [G]win the [C]battle\n\n[Verse 3]\n[C]And though this [F]world with [C]devils [G]filled\nShould [Am]threaten [G]to un[C]do us\n[C]We will not [F]fear for [C]God hath [G]willed\nHis [Am]truth to [G]triumph [C]through us\nThe [Am]Prince of [Em]Darkness [F]grim\nWe [C]tremble [G]not for [Am]him\nHis [F]rage we [C]can en[G]dure\nFor [Am]lo his [F]doom is [G]sure\nOne [F]little [G]word shall [C]fell him',
'C', 0, 110, '4/4', 'Verse1, Verse2, Verse3', 1, TRUE);

-- Song 24: Nearer My God To Thee
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(24, 'Nearer My God To Thee', 'Sarah Adams', 'Lowell Mason', 'english',
'[Verse 1]\nNearer my God to Thee nearer to Thee\nE''en though it be a cross that raiseth me\nStill all my song shall be nearer my God to Thee\nNearer my God to Thee nearer to Thee\n\n[Verse 2]\nThough like the wanderer the sun gone down\nDarkness be over me my rest a stone\nYet in my dreams I''d be nearer my God to Thee\nNearer my God to Thee nearer to Thee\n\n[Verse 3]\nThere let the way appear steps unto heaven\nAll that Thou sendest me in mercy given\nAngels to beckon me nearer my God to Thee\nNearer my God to Thee nearer to Thee',
'[Verse 1]\n[G]Nearer my [C]God to [G]Thee nearer to [D]Thee\n[G]E''en though it [C]be a [G]cross that [D]raiseth [G]me\n[G]Still all my [C]song shall [G]be nearer my [Em]God to [C]Thee\n[G]Nearer my [C]God to [G]Thee [D]nearer to [G]Thee\n\n[Verse 2]\n[G]Though like the [C]wanderer the [G]sun gone [D]down\n[G]Darkness be [C]over [G]me my [D]rest a [G]stone\n[G]Yet in my [C]dreams I''d [G]be nearer my [Em]God to [C]Thee\n[G]Nearer my [C]God to [G]Thee [D]nearer to [G]Thee\n\n[Verse 3]\n[G]There let the [C]way ap[G]pear steps unto [D]heaven\n[G]All that Thou [C]sendest [G]me in [D]mercy [G]given\n[G]Angels to [C]beckon [G]me nearer my [Em]God to [C]Thee\n[G]Nearer my [C]God to [G]Thee [D]nearer to [G]Thee',
'G', 0, 80, '4/4', 'Verse1, Verse2, Verse3', 1, TRUE);

-- Song 25: The Old Rugged Cross
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(25, 'The Old Rugged Cross', 'George Bennard', 'George Bennard', 'english',
'[Verse 1]\nOn a hill far away stood an old rugged cross\nThe emblem of suffering and shame\nAnd I love that old cross where the dearest and best\nFor a world of lost sinners was slain\n\n[Chorus]\nSo I''ll cherish the old rugged cross\nTill my trophies at last I lay down\nI will cling to the old rugged cross\nAnd exchange it someday for a crown\n\n[Verse 2]\nO that old rugged cross so despised by the world\nHas a wondrous attraction for me\nFor the dear Lamb of God left His glory above\nTo bear it to dark Calvary\n\n[Verse 3]\nIn that old rugged cross stained with blood so divine\nA wondrous beauty I see\nFor twas on that old cross Jesus suffered and died\nTo pardon and sanctify me',
'[Verse 1]\nOn a [G]hill far away stood an [C]old rugged [G]cross\nThe [G]emblem of suffering and [D]shame\nAnd I [G]love that old [G7]cross where the [C]dearest and [G]best\nFor a [G]world of lost [D]sinners was [G]slain\n\n[Chorus]\nSo I''ll [D]cherish the old rugged [G]cross\nTill my [C]trophies at last I lay [G]down\nI will [G]cling to the [G7]old rugged [C]cross\nAnd ex[G]change it some[D]day for a [G]crown\n\n[Verse 2]\nO that [G]old rugged cross so de[C]spised by the [G]world\nHas a [G]wondrous attraction for [D]me\nFor the [G]dear Lamb of [G7]God left His [C]glory a[G]bove\nTo [G]bear it to [D]dark Calva[G]ry\n\n[Verse 3]\nIn that [G]old rugged cross stained with [C]blood so di[G]vine\nA [G]wondrous beauty I [D]see\nFor twas [G]on that old [G7]cross Jesus [C]suffered and [G]died\nTo [G]pardon and [D]sanctify [G]me',
'G', 0, 76, '3/4', 'Verse1, Chorus, Verse2, Chorus, Verse3, Chorus', 1, TRUE);

-- Song 26: I Surrender All
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(26, 'I Surrender All', 'Judson Van DeVenter', 'Winfield Weeden', 'english',
'[Verse 1]\nAll to Jesus I surrender\nAll to Him I freely give\nI will ever love and trust Him\nIn His presence daily live\n\n[Chorus]\nI surrender all I surrender all\nAll to Thee my blessed Saviour\nI surrender all\n\n[Verse 2]\nAll to Jesus I surrender\nHumbly at His feet I bow\nWorldly pleasures all forsaken\nTake me Jesus take me now\n\n[Verse 3]\nAll to Jesus I surrender\nMake me Saviour wholly Thine\nLet me feel the Holy Spirit\nTruly know that Thou art mine',
'[Verse 1]\n[G]All to Jesus [C]I sur[G]render\n[G]All to Him I [D]freely give\n[G]I will ever [C]love and [G]trust Him\n[G]In His presence [D]daily [G]live\n\n[Chorus]\n[C]I surrender [G]all [C]I surrender [G]all\n[G]All to Thee my [Em]blessed [Am]Saviour\n[G]I sur[D]render [G]all\n\n[Verse 2]\n[G]All to Jesus [C]I sur[G]render\n[G]Humbly at His [D]feet I bow\n[G]Worldly pleasures [C]all for[G]saken\n[G]Take me Jesus [D]take me [G]now\n\n[Verse 3]\n[G]All to Jesus [C]I sur[G]render\n[G]Make me Saviour [D]wholly Thine\n[G]Let me feel the [C]Holy [G]Spirit\n[G]Truly know that [D]Thou art [G]mine',
'G', 0, 80, '4/4', 'Verse1, Chorus, Verse2, Chorus, Verse3, Chorus', 1, TRUE);

-- Song 27: When I Survey The Wondrous Cross
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(27, 'When I Survey The Wondrous Cross', 'Isaac Watts', 'Lowell Mason', 'english',
'[Verse 1]\nWhen I survey the wondrous cross\nOn which the Prince of glory died\nMy richest gain I count but loss\nAnd pour contempt on all my pride\n\n[Verse 2]\nForbid it Lord that I should boast\nSave in the death of Christ my God\nAll the vain things that charm me most\nI sacrifice them to His blood\n\n[Verse 3]\nSee from His head His hands His feet\nSorrow and love flow mingled down\nDid e''er such love and sorrow meet\nOr thorns compose so rich a crown\n\n[Verse 4]\nWere the whole realm of nature mine\nThat were a present far too small\nLove so amazing so divine\nDemands my soul my life my all',
'[Verse 1]\n[D]When I sur[G]vey the [D]wondrous [A]cross\nOn [D]which the [G]Prince of [A]glory [D]died\nMy [D]richest [G]gain I [D]count but [A]loss\nAnd [D]pour con[G]tempt on [A]all my [D]pride\n\n[Verse 2]\n[D]Forbid it [G]Lord that [D]I should [A]boast\nSave [D]in the [G]death of [A]Christ my [D]God\n[D]All the vain [G]things that [D]charm me [A]most\nI [D]sacri[G]fice them [A]to His [D]blood\n\n[Verse 3]\n[D]See from His [G]head His [D]hands His [A]feet\n[D]Sorrow and [G]love flow [A]mingled [D]down\nDid [D]e''er such [G]love and [D]sorrow [A]meet\nOr [D]thorns com[G]pose so [A]rich a [D]crown\n\n[Verse 4]\n[D]Were the whole [G]realm of [D]nature [A]mine\nThat [D]were a [G]present [A]far too [D]small\n[D]Love so a[G]mazing [D]so di[A]vine\nDe[D]mands my [G]soul my [A]life my [D]all',
'D', 0, 76, '4/4', 'Verse1, Verse2, Verse3, Verse4', 1, TRUE);

-- Song 28: To God Be The Glory
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(28, 'To God Be The Glory', 'Fanny Crosby', 'William Doane', 'english',
'[Verse 1]\nTo God be the glory great things He hath done\nSo loved He the world that He gave us His Son\nWho yielded His life an atonement for sin\nAnd opened the life gate that all may go in\n\n[Chorus]\nPraise the Lord praise the Lord\nLet the earth hear His voice\nPraise the Lord praise the Lord\nLet the people rejoice\nO come to the Father through Jesus the Son\nAnd give Him the glory great things He hath done\n\n[Verse 2]\nO perfect redemption the purchase of blood\nTo every believer the promise of God\nThe vilest offender who truly believes\nThat moment from Jesus a pardon receives',
'[Verse 1]\n[G]To God be the [C]glory great [G]things He hath [D]done\nSo [G]loved He the [C]world that He [G]gave us His [D]Son\nWho [G]yielded His [C]life an a[G]tonement for [Em]sin\nAnd [C]opened the [G]life gate that [D]all may go [G]in\n\n[Chorus]\n[D]Praise the Lord [G]praise the Lord\nLet the [C]earth hear His [G]voice\n[D]Praise the Lord [G]praise the Lord\nLet the [C]people re[D]joice\nO [G]come to the [C]Father through [G]Jesus the [Em]Son\nAnd [C]give Him the [G]glory great [D]things He hath [G]done\n\n[Verse 2]\n[G]O perfect re[C]demption the [G]purchase of [D]blood\nTo [G]every be[C]liever the [G]promise of [D]God\nThe [G]vilest of[C]fender who [G]truly be[Em]lieves\nThat [C]moment from [G]Jesus a [D]pardon re[G]ceives',
'G', 0, 108, '4/4', 'Verse1, Chorus, Verse2, Chorus', 1, TRUE);

-- Song 29: Just As I Am
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(29, 'Just As I Am', 'Charlotte Elliott', 'William Bradbury', 'english',
'[Verse 1]\nJust as I am without one plea\nBut that Thy blood was shed for me\nAnd that Thou bidst me come to Thee\nO Lamb of God I come I come\n\n[Verse 2]\nJust as I am and waiting not\nTo rid my soul of one dark blot\nTo Thee whose blood can cleanse each spot\nO Lamb of God I come I come\n\n[Verse 3]\nJust as I am though tossed about\nWith many a conflict many a doubt\nFightings and fears within without\nO Lamb of God I come I come\n\n[Verse 4]\nJust as I am Thou wilt receive\nWilt welcome pardon cleanse relieve\nBecause Thy promise I believe\nO Lamb of God I come I come',
'[Verse 1]\n[G]Just as I [Em]am with[C]out one [G]plea\nBut [Em]that Thy [C]blood was [D]shed for me\nAnd [G]that Thou [Em]bidst me [C]come to [G]Thee\nO [C]Lamb of [G]God I [D]come I [G]come\n\n[Verse 2]\n[G]Just as I [Em]am and [C]waiting [G]not\nTo [Em]rid my [C]soul of [D]one dark blot\nTo [G]Thee whose [Em]blood can [C]cleanse each [G]spot\nO [C]Lamb of [G]God I [D]come I [G]come\n\n[Verse 3]\n[G]Just as I [Em]am though [C]tossed a[G]bout\nWith [Em]many a [C]conflict [D]many a doubt\n[G]Fightings and [Em]fears with[C]in with[G]out\nO [C]Lamb of [G]God I [D]come I [G]come\n\n[Verse 4]\n[G]Just as I [Em]am Thou [C]wilt re[G]ceive\nWilt [Em]welcome [C]pardon [D]cleanse relieve\nBe[G]cause Thy [Em]promise [C]I be[G]lieve\nO [C]Lamb of [G]God I [D]come I [G]come',
'G', 0, 72, '3/4', 'Verse1, Verse2, Verse3, Verse4', 1, TRUE);

-- Song 30: In The Garden
INSERT INTO songs (song_number, title, artist, composer, language, lyrics_original, chords, original_key, capo, bpm, time_signature, structure, created_by, is_active) VALUES
(30, 'In The Garden', 'C. Austin Miles', 'C. Austin Miles', 'english',
'[Verse 1]\nI come to the garden alone\nWhile the dew is still on the roses\nAnd the voice I hear falling on my ear\nThe Son of God discloses\n\n[Chorus]\nAnd He walks with me and He talks with me\nAnd He tells me I am His own\nAnd the joy we share as we tarry there\nNone other has ever known\n\n[Verse 2]\nHe speaks and the sound of His voice\nIs so sweet the birds hush their singing\nAnd the melody that He gave to me\nWithin my heart is ringing\n\n[Verse 3]\nI''d stay in the garden with Him\nThough the night around me be falling\nBut He bids me go through the voice of woe\nHis voice to me is calling',
'[Verse 1]\nI [C]come to the garden a[F]lone\nWhile the [C]dew is still on the [G]roses\nAnd the [C]voice I hear falling [F]on my ear\nThe [C]Son of [G]God dis[C]closes\n\n[Chorus]\nAnd He [G]walks with me and He [C]talks with me\nAnd He [F]tells me I am His [C]own\nAnd the [F]joy we [C]share as we [Am]tarry [Dm]there\n[C]None other has [G]ever [C]known\n\n[Verse 2]\nHe [C]speaks and the sound of His [F]voice\nIs so [C]sweet the birds hush their [G]singing\nAnd the [C]melody that He [F]gave to me\nWith[C]in my [G]heart is [C]ringing\n\n[Verse 3]\nI''d [C]stay in the garden with [F]Him\nThough the [C]night around me be [G]falling\nBut He [C]bids me go through the [F]voice of woe\nHis [C]voice to [G]me is [C]calling',
'C', 0, 76, '3/4', 'Verse1, Chorus, Verse2, Chorus, Verse3, Chorus', 1, TRUE);

-- =============================================
-- Link Hymns 16-30 to Hashtags
-- =============================================
INSERT IGNORE INTO song_hashtags (song_id, hashtag_id) VALUES
((SELECT id FROM songs WHERE title='Holy Holy Holy'), (SELECT id FROM hashtags WHERE name='worship')),
((SELECT id FROM songs WHERE title='Holy Holy Holy'), (SELECT id FROM hashtags WHERE name='adoration')),
((SELECT id FROM songs WHERE title='Holy Holy Holy'), (SELECT id FROM hashtags WHERE name='praise')),
((SELECT id FROM songs WHERE title='Holy Holy Holy'), (SELECT id FROM hashtags WHERE name='classic')),
((SELECT id FROM songs WHERE title='It Is Well With My Soul'), (SELECT id FROM hashtags WHERE name='peace')),
((SELECT id FROM songs WHERE title='It Is Well With My Soul'), (SELECT id FROM hashtags WHERE name='comfort')),
((SELECT id FROM songs WHERE title='It Is Well With My Soul'), (SELECT id FROM hashtags WHERE name='faith')),
((SELECT id FROM songs WHERE title='It Is Well With My Soul'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='Be Thou My Vision'), (SELECT id FROM hashtags WHERE name='devotional')),
((SELECT id FROM songs WHERE title='Be Thou My Vision'), (SELECT id FROM hashtags WHERE name='prayer')),
((SELECT id FROM songs WHERE title='Be Thou My Vision'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='Come Thou Fount Of Every Blessing'), (SELECT id FROM hashtags WHERE name='praise')),
((SELECT id FROM songs WHERE title='Come Thou Fount Of Every Blessing'), (SELECT id FROM hashtags WHERE name='thanksgiving')),
((SELECT id FROM songs WHERE title='Come Thou Fount Of Every Blessing'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='Rock Of Ages'), (SELECT id FROM hashtags WHERE name='cross')),
((SELECT id FROM songs WHERE title='Rock Of Ages'), (SELECT id FROM hashtags WHERE name='salvation')),
((SELECT id FROM songs WHERE title='Rock Of Ages'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='Joyful Joyful We Adore Thee'), (SELECT id FROM hashtags WHERE name='praise')),
((SELECT id FROM songs WHERE title='Joyful Joyful We Adore Thee'), (SELECT id FROM hashtags WHERE name='joy')),
((SELECT id FROM songs WHERE title='Joyful Joyful We Adore Thee'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='Crown Him With Many Crowns'), (SELECT id FROM hashtags WHERE name='praise')),
((SELECT id FROM songs WHERE title='Crown Him With Many Crowns'), (SELECT id FROM hashtags WHERE name='adoration')),
((SELECT id FROM songs WHERE title='Crown Him With Many Crowns'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='A Mighty Fortress Is Our God'), (SELECT id FROM hashtags WHERE name='faith')),
((SELECT id FROM songs WHERE title='A Mighty Fortress Is Our God'), (SELECT id FROM hashtags WHERE name='victory')),
((SELECT id FROM songs WHERE title='A Mighty Fortress Is Our God'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='Nearer My God To Thee'), (SELECT id FROM hashtags WHERE name='devotional')),
((SELECT id FROM songs WHERE title='Nearer My God To Thee'), (SELECT id FROM hashtags WHERE name='prayer')),
((SELECT id FROM songs WHERE title='Nearer My God To Thee'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='The Old Rugged Cross'), (SELECT id FROM hashtags WHERE name='cross')),
((SELECT id FROM songs WHERE title='The Old Rugged Cross'), (SELECT id FROM hashtags WHERE name='salvation')),
((SELECT id FROM songs WHERE title='The Old Rugged Cross'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='I Surrender All'), (SELECT id FROM hashtags WHERE name='dedication')),
((SELECT id FROM songs WHERE title='I Surrender All'), (SELECT id FROM hashtags WHERE name='worship')),
((SELECT id FROM songs WHERE title='I Surrender All'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='When I Survey The Wondrous Cross'), (SELECT id FROM hashtags WHERE name='cross')),
((SELECT id FROM songs WHERE title='When I Survey The Wondrous Cross'), (SELECT id FROM hashtags WHERE name='salvation')),
((SELECT id FROM songs WHERE title='When I Survey The Wondrous Cross'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='To God Be The Glory'), (SELECT id FROM hashtags WHERE name='praise')),
((SELECT id FROM songs WHERE title='To God Be The Glory'), (SELECT id FROM hashtags WHERE name='thanksgiving')),
((SELECT id FROM songs WHERE title='To God Be The Glory'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='Just As I Am'), (SELECT id FROM hashtags WHERE name='salvation')),
((SELECT id FROM songs WHERE title='Just As I Am'), (SELECT id FROM hashtags WHERE name='dedication')),
((SELECT id FROM songs WHERE title='Just As I Am'), (SELECT id FROM hashtags WHERE name='hymn')),
((SELECT id FROM songs WHERE title='In The Garden'), (SELECT id FROM hashtags WHERE name='devotional')),
((SELECT id FROM songs WHERE title='In The Garden'), (SELECT id FROM hashtags WHERE name='fellowship')),
((SELECT id FROM songs WHERE title='In The Garden'), (SELECT id FROM hashtags WHERE name='hymn'));
