{t:E-0054 (G) BY HIS WORD, I HAVE NOT FEAR IN ME}
{st:}

E-0054 | G Chord 

BY HIS WORD, I HAVE NO FEAR IN ME 
BY HIS WORD, DEATH CANNOT SWALLOW ME 
BY HIS WORD, I HAVE PROSPERITY 
BY HIS WORD, SICKNESS CAN'T DWELL IN ME 
BY HIS WORD, I WALK IN VICTORY 
BY HIS WORD, I'VE BEEN SET FREE. 

2, BY HIS NAME 
3. BY HIS BLOOD




{tempo:120}

{key:G}

{scrollspeed:6}
