{t:E-1023 (A) Lord I lift your name on High}
{st:}

SONG 1023
CHORD A 

LORD I LIFT YOUR NAME ON HIGH
LORD I LOVE TO SING YOUR PRAISES
I'M SO GLAD YOU ARE IN MY LIFE
I'M SO GLAD YOU CAME TO SAVE US
YOU CAME FROM HEAVEN TO EARTH, TO SHOW THE WAY
FROM THE EARTH TO THE CROSS, MY DEBT TO PAY
FROM THE CROSS TO THE GRAVE, FROM THE GRAVE TO THE SKY
LORD I LIFT YOUR NAME ON HIGH



{genre:Praise}
{notes:E-1023}




{tempo:0}

{key:G}

{scrollspeed:6}
